from .ernie_mappings import ERNIE_PARAMETER_MAPPING, ERNIE_VALUE_TRANSFORMS
from .qwen_mappings import QWEN_PARAMETER_MAPPING, QWEN_VALUE_TRANSFORMS

__all__ = [
    "ERNIE_PARAMETER_MAPPING",
    "ERNIE_VALUE_TRANSFORMS",
    "QWEN_PARAMETER_MAPPING",
    "QWEN_VALUE_TRANSFORMS",
]
